export default {
  testEnvironment: 'jsdom',
  setupFiles: ['<rootDir>/src/jest.setup.js'],
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(png|jpg|jpeg|gif|svg|webp)$': '<rootDir>/__mocks__/fileMock.js',
  },
  testMatch: [
    '**/tests/unit/**/*.test.[jt]s?(x)',
  ],
  collectCoverageFrom: [
    'src/**/*.{js,jsx}',
    '!src/main.jsx',
    '!src/mocks/**',
    '!src/data/**',
    '!src/api/graphql/**',
    '!src/api/rest/**',
    '!src/api/index.js',
    '!src/context/**',
    '!src/models/**',
    '!src/pages/**',
    '!src/store/store.js',
    '!src/components/layout/**',
    '!src/App.jsx',
    '!src/hooks/useGraphQL.js',
    '!src/components/ui/ErrorMessage.jsx',
    '!src/components/citas/CitasList.jsx',
    '!src/components/clientes/ClientesList.jsx',
    '!src/components/clientes/ClienteDetalle.jsx',
    '!src/components/mascotas/MascotasList.jsx',
    '!src/components/mascotas/MascotaCard.jsx',
    '!src/components/mascotas/HistorialMedico.jsx',
  ],
  coverageThreshold: {
    global: { lines: 70 },
  },
};